#!/usr/bin/env bash
set -xeuo pipefail

gradle -PHIFI_ANDROID_PRECOMPILED=$PWD/libs -PRELEASE_NUMBER=${RELEASE_NUMBER} -PRELEASE_TYPE=${RELEASE_TYPE} setupDependencies
gradle -PHIFI_ANDROID_PRECOMPILED=$PWD/libs -PRELEASE_NUMBER=${RELEASE_NUMBER} -PRELEASE_TYPE=${RELEASE_TYPE} app:${ANDROID_BUILD_TARGET}
